version: '3.8'

services:

    nginx:
      image: nginx:1.19.0-alpine
      volumes:
        - nginx-configs:/etc/nginx/conf.d/
      ports:
        - 80:80
      depends_on:
        - ruby_backend

    postgresql:
        image: postgres
        volumes:
            - postgres:/var/lib/postgresql/data/
            - backups_data:/var/backups/
        env_file: 
            - /opt/.env

    ruby_backend:
        # set your image name
        image: ghcr.io/oleksandrtimoshenko/ruby_backend
        environment:
            - DBHOST=postgresql
        command: ./entrypoint.sh
        depends_on:
          - postgresql
        env_file:
          - /opt/.env

volumes:
    postgres:
    backups_data:
    nginx-configs:
      driver_opts:
        type: none
        device: /opt/nginx/
        o: bind
