version: '3.8'

services:
    postgresql:
        image: postgres
        volumes:
            - postgres:/var/lib/postgresql/data/
            - backups_data:/var/backups/
        ports:
          - 5432:5432
        env_file: 
            - ../../.env

    ruby_backend:
        image: ruby_backend
        command: ./entrypoint.sh
        ports:
          - 3000:3000
        env_file:
          - ../../.env

volumes:
    postgres:
    backups_data:
