default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: backend_development
  username: <%= ENV['DBUSER'] %>
  password: <%= ENV['DBPASS'] %>
  host:     <%= ENV['DBHOST'] %>
  port:     <%= ENV['DBPORT']%>

test:
  <<: *default
  database: backend_test
  username: <%= ENV['DBUSER'] %>
  password: <%= ENV['DBPASS'] %>
  host:     <%= ENV['DBHOST'] %>

production:
  <<: *default
  database: backend_development
  username: <%= ENV['DBUSER'] %>
  password: <%= ENV['DBPASS'] %>
  host:     <%= ENV['DBHOST'] %>
  port:     <%= ENV['DBPORT']%>
